if(@ARGV==0) {
    print STDERR "This utility submits jobs to the queue based on a make file generated by IPSA\n";
    print STDERR "The first argument is the target colmmon name (A01 etc)\n";
    exit;
}

while($line=<STDIN>) {
    chomp $line;
    if($line=~/\:/) {
	($targets, $depends) = split /\s+\:+\s+/, $line;
	@targets = split /\s+/, $targets;
	@depends = split /\s+/, $depends;
	foreach $t(@targets) {
	    foreach $d(@depends) {
		$DEPEND{$t}{$d}=T;
	    }
	}
    }
    if($line=~/^\t/) {
	foreach $t(@targets) {
	    $RECIPE{$t}.=substr($line,1)."\n" if($line=~/\w/);
	}
    }
}

$t = $ARGV[0];
$preamble="#!/bin/bash\n#\$ -soft\n#\$ -cwd\nexport PERL5LIB=~/ipsa\n";
$dir = "submit$$/";
system("rm -f -r $dir; mkdir -p $dir");

$N = $ARGV[1];
$n=0;
foreach $d(keys(%{$DEPEND{$t}})) {
    next if($d=~/\.log$/);
    push @{$stack[$n]}, $RECIPE{$d};
    $n++ if(@{$stack[$n]}>$N);
     $j++;
}
print STDERR $j;

for($i=0;$i<=$n;$i++) {
    $sh = $dir."job$i.sh";
    open FILE, ">$sh";
    print FILE $preamble, join("\n",@{$stack[$i]});
    close FILE;
    system "chmod +x $sh";
    print "qsub $sh\n";
}

